# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('PR', 'Private'), ('PB', 'Public')], default='PR', max_length=3)),
            ],
            options={
                'db_table': 'post_table',
            },
        ),
    ]
